### ISSUE TITLE
publishing per tranlsation

### ISSUE THREAD

**Issue by bashu** [django-fluent/django-fluent-pages#70]
right now if you publish for example English translation, then all other will be counted as published and vice verse, is it possible to fix? where to start?

**Comment by vdboor** [comment]
Yes that would be possible.

This was done in the past to make it easy to query for published pages (plus the cms didn't have translations at first). In my experience, things get really complex when each translation has it's own published status. However I'm eager to have a good solution for this.

The biggest issue is likely, can you still query all pages that are published (e.g. to display in a menu), because you need to fetch both the pages with a published fallback or published translation.

An advanced addition to this would be a versioning system where you can preview changes first, and then publish them.
